name: Scopes Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  linux:
    runs-on: ubuntu-22.04
    outputs:
      revision: ${{ steps.revision.outputs.scopes-revision }}
    steps:
      - id: revision
        run: |
          hg clone -U https://hg.sr.ht/~duangle/scopes/
          pushd scopes
          echo "::set-output name=scopes-revision::$(hg id -r tip -T '{node|short}')"
          popd
      - name: Install build dependencies
        run: sudo apt install mkdocs python3-pip libtinfo5
      - name: Build
        run: |
          curl https://hg.sr.ht/~duangle/majoreo/raw/eo | python3 - init majoreo && ./bin/eo import scopes
          ./bin/eo install -y scopes-unstable
          rm ./bin/eo
          tar -czf scopes-unstable-linux-${{ steps.revision.outputs.scopes-revision }}.tar.gz bin/ doc/ include/ lib/ testing/ CREDITS.md LICENSE.md
      - name: Distribution Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scopes-unstable-linux-${{ steps.revision.outputs.scopes-revision }}
          path: scopes-unstable-linux-${{ steps.revision.outputs.scopes-revision }}.tar.gz
      - name: Standalone Documentation
        uses: actions/upload-artifact@v3
        with:
          name: scopes-unstable-docs-${{ steps.revision.outputs.scopes-revision }}
          path: doc/
  windows:
    runs-on: windows-latest
    needs: linux
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      - name: Install build dependencies
        run: pacman -S --noconfirm make mingw64/mingw-w64-x86_64-python mingw64/mingw-w64-x86_64-python-pip zip  mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-libxml2
      - name: Build
        run: |
          mkdir bin
          wget "https://hg.sr.ht/~duangle/majoreo/raw/build/dist/windows/eo.exe?rev=tip" -O ./bin/eo.exe
          mkdir recipes
          wget "https://hg.sr.ht/~duangle/scopes/raw/extras/eo/scopes.eo?rev=tip" -O recipes/scopes.eo
          ./bin/eo init
          ./bin/eo install -y scopes-source-unstable
          ./build.sh
      - name: Cleanup
        run: |
          rm -r doc # we don't need the data for making the docs, and we'll copy them from the linux generated ones.
          mkdir doc
          rm ./bin/eo ./bin/eo.exe
      - uses: actions/download-artifact@v3
        with:
          name: scopes-unstable-docs-${{ needs.linux.outputs.revision }}
          path: doc
      - run: zip -r scopes-unstable-windows-${{ needs.linux.outputs.revision }}.zip bin/ doc/ include/ lib/ testing/ CREDITS.md LICENSE.md
      - name: Distribution Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scopes-unstable-windows-${{ needs.linux.outputs.revision }}
          path: scopes-unstable-windows-${{ needs.linux.outputs.revision }}.zip
