name: Scopes Nightly Windows
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
      - name: Install build dependencies
        run: pacman -S --noconfirm make mingw64/mingw-w64-x86_64-python mingw64/mingw-w64-x86_64-python-pip
      - run: curl https://hg.sr.ht/~duangle/majoreo/raw/eo | python3 - init majoreo && ./bin/eo import scopes
      - run: ./bin/eo install -y scopes-unstable
      - run: rm ./bin/eo
      - run: mkdir scopes-unstable
      - run: mv bin/ doc/ include/ lib/ testing/ CREDITS.md LICENSE.md scopes-unstable/
      - name: Distribution Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scopes-unstable
          path: scopes-unstable/
